ASSIGNMENT PANDAS AND NUMPY

---

Follow the instructions below:

>1. Generate an array of zeroes using inbuilt numpy function
>2. Run the given code and find the dot produckt of both arrays:

>>>import numpy as np

>>>a = np.random.randint(2,10, (3,4))

>>>b = np.random.randint(2,10, (4,3))

>>>print("A: \n",a)

>>>print("B: \n",b)

>>>print()

>>>print("A DOT B:")

>>>a.dot(b)

>3. Read tge csv file provided using pandas and display the first 5 entries.
4.Describe the data with all features.
5. Find the total count of missing values for each feature.
6. Display all the unique values from the 'DESCRIPTION' column
7. Create a grouped table using 'Description' as the grouping column with the means of all other columns.
8. Generate a randi sample of 10 rows from the data.
9. Add a feature called 'New_Feature' to the Dataset and add random float values in between 0 and 1 using NUMPY.
10. Replace zero value of column 'OBJECTID' with mean value permanently


In [5]:
#1
data_path="/content/drive/MyDrive/data.csv"
import numpy as np
n=int(input("Enter size of zero array: "))
z=np.zeros(n)
z

Enter size of zero array: 5


array([0., 0., 0., 0., 0.])

In [10]:
#2
a = np.random.randint(2,10, (3,4))
b = np.random.randint(2,10, (4,3))
print("A: \n",a)
print("B: \n",b)
print()
print("A DOT B:")
a.dot(b)

A: 
 [[5 3 6 5]
 [9 4 3 2]
 [7 5 3 9]]
B: 
 [[5 8 5]
 [3 4 2]
 [5 3 6]
 [3 9 3]]

A DOT B:


array([[ 79, 115,  82],
       [ 78, 115,  77],
       [ 92, 166,  90]])

**3.Read tge csv file provided using pandas and display the first 5 entries.**

In [14]:
#3
import pandas as pd
df=pd.read_csv(data_path)
df.head()

OBJECTID                        UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
0        21        Fort Stevenson State Park  ...   0.000284   0.135641
1        22           Beaver Lake State Park  ...   0.000129   0.080067
2        23  Fort Abraham Lincoln State Park  ...   0.000399   0.119868
3        24           Fort Ransom State Park  ...   0.000444   0.128733
4        25        Grahams Island State Park  ...   0.000469   0.125546

[5 rows x 6 columns]

**4. Describe the data with all features.**

In [62]:
#4
df.describe()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
count  25.000000    25.000000   25.000000  25.000000
mean   33.480000   724.134400    0.000352   0.109863
std     6.922909  1275.490247    0.000617   0.089073
min    22.000000    11.400000    0.000005   0.009396
25%    28.000000    72.300000    0.000034   0.033885
50%    33.000000   524.810000    0.000256   0.087192
75%    39.000000   836.470000    0.000399   0.145220
max    45.000000  6492.930000    0.003136   0.338800

**5. Find the total count of missing values for each feature.**

In [15]:
#5
df.isnull().sum()

OBJECTID       0
UNIT_NAME      0
DESCRIPTION    0
ACRES          0
SHAPE.AREA     0
SHAPE.LEN      0
dtype: int64

**6. Display all the unique values from the 'DESCRIPTION' column**

In [26]:
#6
df.DESCRIPTION.unique()

array(['State Park', 'Interpretive Center', 'State Recreation Area',
       'State Natural Area', 'State Nature Preserve'], dtype=object)

**7. Create a grouped table using 'Description' as the grouping column with the means of all other columns.**

In [63]:
#7
df.groupby("DESCRIPTION").mean()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
DESCRIPTION                                                         
Interpretive Center    29.000000    14.710000    0.000007   0.016774
State Natural Area     39.000000   219.615000    0.000105   0.077137
State Nature Preserve  39.500000    84.095000    0.000041   0.037175
State Park             29.461538  1168.668462    0.000567   0.150326
State Recreation Area  38.285714   326.934286    0.000162   0.078135

**8. Generate a random sample of 10 rows from the data.**

In [30]:
#8
df.sample(n=10)

OBJECTID                              UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
0         21              Fort Stevenson State Park  ...   0.000284   0.135641
21        43    Pembina Gorge State Recreation Area  ...   0.000615   0.338800
17        38    Fahlgren Park State Recreation Area  ...   0.000010   0.013294
8         29    Lewis and Clark Interpretive Center  ...   0.000007   0.016774
7         28             Lewis and Clark State Park  ...   0.000256   0.130420
13        36  Crow Flies High State Recreation Area  ...   0.000120   0.050518
22        44  Turtle Mountain State Recreation Area  ...   0.000345   0.086487
11        32                 Sully Creek State Park  ...   0.000030   0.024016
23        45                 Cross Ranch State Park  ...   0.000274   0.180257
5         26                   Icelandic State Park  ...   0.000461   0.166712

[10 rows x 6 columns]

**9. Add a feature called 'New_Feature' to the Dataset and add random float values in between 0 and 1 using NUMPY.**

In [40]:
#9
a=np.random.rand(len(df))
df1=df.assign(NEW_FEATURE=list(a))
df1

OBJECTID  ... NEW_FEATURE
0         21  ...    0.235392
1         22  ...    0.086922
2         23  ...    0.228666
3         24  ...    0.116243
4         25  ...    0.550975
5         26  ...    0.752315
6         27  ...    0.432320
7         28  ...    0.802202
8         29  ...    0.579509
9         30  ...    0.399894
10        31  ...    0.194132
11        32  ...    0.012112
12        35  ...    0.923676
13        36  ...    0.757428
14        33  ...    0.957800
15        34  ...    0.265411
16        37  ...    0.140561
17        38  ...    0.547489
18        39  ...    0.622661
19        40  ...    0.628931
20        41  ...    0.347300
21        43  ...    0.795377
22        44  ...    0.743799
23        45  ...    0.056865
24        42  ...    0.883713

[25 rows x 7 columns]

**10. Replace zero value of column 'OBJECTID' with mean value permanently**


In [61]:
#10
df=pd.read_csv(data_path)
m=df["OBJECTID"].mean()
df["OBJECTID"][0]=m
df

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


OBJECTID                                   UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
0         33                   Fort Stevenson State Park  ...   0.000284   0.135641
1         22                      Beaver Lake State Park  ...   0.000129   0.080067
2         23             Fort Abraham Lincoln State Park  ...   0.000399   0.119868
3         24                      Fort Ransom State Park  ...   0.000444   0.128733
4         25                   Grahams Island State Park  ...   0.000469   0.125546
5         26                        Icelandic State Park  ...   0.000461   0.166712
6         27                   Lake Metigoshe State Park  ...   0.000751   0.212196
7         28                  Lewis and Clark State Park  ...   0.000256   0.130420
8         29         Lewis and Clark Interpretive Center  ...   0.000007   0.016774
9         30           Fort Mandan State Recreation Area  ...   0.000005   0.009396
10        31                  Little Missouri State Park  ...   0.003136   0.313756
11        32                      Sully Creek State Park  ...   0.000030   0.024016
12        35        Butte St. Paul State Recreation Area  ...   0.000025   0.022095
13        36       Crow Flies High State Recreation Area  ...   0.000120   0.050518
14        33                     Turtle River State Park  ...   0.000378   0.145220
15        34                   Lake Sakakawea State Park  ...   0.000357   0.191806
16        37                  Elkhorn State Natural Area  ...   0.000127   0.067082
17        38         Fahlgren Park State Recreation Area  ...   0.000010   0.013294
18        39             Gunlogson State Nature Preserve  ...   0.000048   0.040465
19        40  Head of the Mountain State Nature Preserve  ...   0.000034   0.033885
20        41           Missouri River State Natural Area  ...   0.000083   0.087192
21        43         Pembina Gorge State Recreation Area  ...   0.000615   0.338800
22        44       Turtle Mountain State Recreation Area  ...   0.000345   0.086487
23        45                      Cross Ranch State Park  ...   0.000274   0.180257
24        42         Pelican Point State Recreation Area  ...   0.000013   0.026357

[25 rows x 6 columns]